const Koa = require('koa')
const convert = require('koa-convert')
const loggerGenerator = require('./middleware/logger-generator')
const jsonAdapter = require('./middleware/json-adapter')
const bodyParser = require('koa-bodyparser')
const controller = require('./middleware/controllers')
const koaValidator = require('koa-middle-validator')
const app = new Koa()
app.use(convert(loggerGenerator()))
app.use(convert(jsonAdapter()))
app.use(bodyParser())
app.use(koaValidator())
app.use(controller())

app.listen(3000)
console.log('[demo] start-quick is starting at port 3000')